healthComponent = new HealthComponent(self, { maxHp: 8 })
xpComponent = new XpComponent(self, { xp: 2 })
bulletData = new BulletData(self)
bulletAttack = new AttackComponent(self, obj_player, new BulletAttack(), bulletData)
knifeData = new KnifeData(self)
knifeAttack = new AttackComponent(self, obj_player, new KnifeAttack(), knifeData)
