healthComponent = new HealthComponent(self, { maxHp: 20 })
bulletData = new BulletData(self)
bulletAttack = new AttackComponent(self, new BulletAttack(), bulletData)
knifeData = new KnifeData(self)
knifeAttack = new AttackComponent(self, new KnifeAttack(), knifeData)
